name: Build BusyBox for Mobile OS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  busybox-compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Cross-Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu build-essential git make bzip2

    - name: Download BusyBox Source
      run: |
        git clone --depth 1 --branch 1_36_stable https://git.busybox.net/busybox

    - name: Configure BusyBox (Static Build)
      run: |
        cd busybox
        # Derleyiciyi baştan tanımlayarak konfigüre ediyoruz
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
        
        # Statik binary olarak kilitliyoruz
        sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config

    - name: Compile and Install
      run: |
        cd busybox
        # Hata veren kısım burasıydı; HOSTCC ve CC parametrelerini açıkça dikte ediyoruz
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=aarch64-linux-gnu-gcc HOSTCC=gcc -j$(nproc) install

    - name: Create Linux RootFS Structure
      run: |
        mkdir -p rootfs/{bin,sbin,etc,proc,sys,usr/bin,usr/sbin,dev,root}
        cp -av busybox/_install/* rootfs/
        
        mkdir -p rootfs/etc/init.d
        cat << 'EOF' > rootfs/etc/init.d/rcS
        #!/bin/sh
        mount -t proc none /proc
        mount -t sysfs none /sys
        mount -t devtmpfs none /dev
        echo "========================================"
        echo "  MOBILES OS ARKA PLAN MOTORU CALISTI!  "
        echo "========================================"
        /bin/sh
        EOF
        chmod +x rootfs/etc/init.d/rcS

    - name: Pack RootFS Tarball
      run: |
        tar -cvzf rootfs.tar.gz -C rootfs .

    - name: Upload BusyBox RootFS
      uses: actions/upload-artifact@v4
      with:
        name: rpi4-busybox-rootfs
        path: rootfs.tar.gz
